### ISSUE TITLE
Mockup: User config

### ISSUE THREAD

**Issue by thepaulaseoane** [dani17b/web-productivio#39]

**Comment by IsFriskis** [comment]
![image](https://user-images.githubusercontent.com/118571834/226836615-c1ed680f-b082-4692-803f-d76f1cdc836e.png)

**Comment by thepaulaseoane** [comment]
- Se podría alargar el botón de cambiar contraseña para que ocupe toda la columna, igual que los inputs. 
- En los inputs dejaría la letra en regular en lugar de en negrita y la haría algo más pequeña que los títulos (igualando el tamaño de letra del botón y de los  inputs). 
- El icono de guardar debería ir en blanco.
¡Por lo demás todo guay! :)

**Comment by IsFriskis** [comment]
![image](https://user-images.githubusercontent.com/118571834/228201692-1712c45f-a113-4fee-b28f-7b542b2fc497.png)

**Comment by thepaulaseoane** [comment]
¡Genial! 😄
