### ISSUE TITLE
Mockup: Update task

### ISSUE THREAD

**Issue by thepaulaseoane** [dani17b/web-productivio#40]

**Comment by thepaulaseoane** [comment]
_Update task_ page. It should allow the user to change the task's status, as well as the progress bar. They should also be able to change the name and description of the task.

**Comment by thepaulaseoane** [comment]
![Image](https://user-images.githubusercontent.com/126391932/226362797-c22d947c-64fa-4152-8ab7-1071ec33afed.png)

**Comment by ariashector19** [comment]
muy bonito
