### ISSUE TITLE
Mockup: View comments/comment

### ISSUE THREAD

**Issue by thepaulaseoane** [dani17b/web-productivio#41]

**Comment by FerV02** [comment]
Mockup de la sección de comentarios implementada dentro del home:

![image](https://user-images.githubusercontent.com/116814534/226372187-7c7314e1-677a-42d6-b38f-4b5f1ee762c7.png)

**Comment by thepaulaseoane** [comment]
Colocaría los iconos de los comentarios debajo del de comentarios o entre comentarios y like y dejaría algo más de margen respecto al lado derecho

**Comment by FerV02** [comment]
![image](https://user-images.githubusercontent.com/116814534/228194557-96f999ba-4f8f-428f-b9a4-6429ac8ab86f.png)
