### ISSUE TITLE
Mockup: View user 

### ISSUE THREAD

**Issue by thepaulaseoane** [dani17b/web-productivio#42]
This mockup is meant to show how another user's profile will be displayed. It should look different from the user's profile and it should include a _Add friend_ button.

**Comment by FerV02** [comment]
Mockup realizado:
![image](https://user-images.githubusercontent.com/116814534/226550530-b474be2f-c0b2-446e-853e-cd14249d13d4.png)

**Comment by FerV02** [comment]
Mockup realizado:
![image](https://user-images.githubusercontent.com/116814534/226550725-908efc7b-a4d4-449f-ac9e-4196b302681b.png)
